name: chocolatine
on: [push]
jobs:
  Explore-Github-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: find unwanted files
        if: find . -type f -name "*~" -o -name "#*#" -o -name "*.o" -o -name "*.a" -o -name "*.so" -o -name "*.gcno" -o -name "*.gcda" -o -name "*.gcov" -o -name "*pain_au_chocolat.*" -o -name "*-" -o -name "tmp/*"
        ABORT: "Found unwanted files"
      - name: check_program_compilation
          - run: make
          - run: make clean
      - name: run_tests
          - run: make tests_run
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:EpitechPromo2026/B-DOP-200-TLS-2-1-chocolatine-matheo.martin.git
          ssh_private_key:
            ${{ secrets.Key }}