name: chocolatine
on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
  job2:
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
      #- name: find_unwanted_files
      - uses: docker://epitechcontent/epitest-docker:latest
      - run: printf "Hello world"
      #if: ${{find . -type f -name "*~" -o -name "#*#" -o -name "*.o" -o -name "*.a" -o -name "*.so" -o -name "*.gcno" -o -name "*.gcda" -o -name "*.gcov" -o -name "*pain_au_chocolat.*" -o -name "*-" -o -name "tmp/*"}}
      #ABORT: "Found unwanted files"
  job3:
    runs-on: ubuntu-latest
    needs: [job2]
    steps:
      - name: check_program_compilation
      - uses: docker://epitechcontent/epitest-docker:latest
      - run: make
      - run: make clean
  job4:
    runs-on: ubuntu-latest
    needs: [job3]
    steps:
      - name: run_tests
        uses: docker://epitechcontent/epitest-docker:latest
      - run: make tests_run
  job5:
    runs-on: ubuntu-latest
    needs: [job4]
    steps:
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:EpitechPromo2026/B-DOP-200-TLS-2-1-chocolatine-matheo.martin.git
          ssh_private_key:
            ${{ secrets.Key }}